packages:
  - apps/*
  - packages/*

allowBuilds:
  '@parcel/watcher': true
  bufferutil: false
  core-js: false
  esbuild: true
  sharp: true
  utf-8-validate: false
  workerd: true
minimumReleaseAgeExclude:
  - '@cloudflare/vite-plugin@1.51.0'
  - miniflare@5.20260801.0-alpha || 5.20260828.0-alpha
  - ultracite@7.10.1
  - wrangler@4.119.0 || 4.127.1
  - '@clerk/cli-darwin-arm64@3.1.0'
  - '@clerk/cli-darwin-x64@3.1.0'
  - '@clerk/cli-linux-arm64-musl@3.1.0'
  - '@clerk/cli-linux-arm64@3.1.0'
  - '@clerk/cli-linux-x64-musl@3.1.0'
  - '@clerk/cli-linux-x64@3.1.0'
  - '@clerk/cli-win32-arm64@3.1.0'
  - '@clerk/cli-win32-x64@3.1.0'
  - clerk@3.1.0
  - '@cloudflare/vitest-plugin@1.1.2'
  - '@cloudflare/workerd-darwin-64@1.20260828.1'
  - '@cloudflare/workerd-darwin-arm64@1.20260828.1'
  - '@cloudflare/workerd-linux-64@1.20260828.1'
  - '@cloudflare/workerd-linux-arm64@1.20260828.1'
  - '@cloudflare/workerd-windows-64@1.20260828.1'
  - workerd@1.20260828.1
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
