/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioRouteImport } from './routes/_studio'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as StudioArticlesRouteImport } from './routes/_studio.articles'
import { Route as StudioCommunitiesRouteImport } from './routes/_studio.communities'
import { Route as StudioHomepageRouteImport } from './routes/_studio.homepage'
import { Route as StudioPagesRouteImport } from './routes/_studio.pages'
import { Route as StudioPeopleRouteImport } from './routes/_studio.people'
import { Route as StudioTeamRouteImport } from './routes/_studio.team'
import { Route as ApiMediaRouteImport } from './routes/api/media'
import { Route as StudioArticlesIndexRouteImport } from './routes/_studio.articles.index'
import { Route as StudioArticlesArticleIdRouteImport } from './routes/_studio.articles.$articleId'
import { Route as StudioPagesIndexRouteImport } from './routes/_studio.pages.index'
import { Route as StudioPagesArticleIdRouteImport } from './routes/_studio.pages.$articleId'
import { Route as ApiMediaIdRouteImport } from './routes/api/media.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/_studio',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioArticlesRoute = StudioArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => StudioRoute,
} as any)
const StudioCommunitiesRoute = StudioCommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => StudioRoute,
} as any)
const StudioHomepageRoute = StudioHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => StudioRoute,
} as any)
const StudioPagesRoute = StudioPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => StudioRoute,
} as any)
const StudioPeopleRoute = StudioPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => StudioRoute,
} as any)
const StudioTeamRoute = StudioTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => StudioRoute,
} as any)
const ApiMediaRoute = ApiMediaRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioArticlesIndexRoute = StudioArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioArticlesRoute,
} as any)
const StudioArticlesArticleIdRoute = StudioArticlesArticleIdRouteImport.update({
  id: '/$articleId',
  path: '/$articleId',
  getParentRoute: () => StudioArticlesRoute,
} as any)
const StudioPagesIndexRoute = StudioPagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioPagesRoute,
} as any)
const StudioPagesArticleIdRoute = StudioPagesArticleIdRouteImport.update({
  id: '/$articleId',
  path: '/$articleId',
  getParentRoute: () => StudioPagesRoute,
} as any)
const ApiMediaIdRoute = ApiMediaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiMediaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/sign-in': typeof SignInRoute
  '/articles': typeof StudioArticlesRouteWithChildren
  '/communities': typeof StudioCommunitiesRoute
  '/homepage': typeof StudioHomepageRoute
  '/pages': typeof StudioPagesRouteWithChildren
  '/people': typeof StudioPeopleRoute
  '/team': typeof StudioTeamRoute
  '/api/media': typeof ApiMediaRouteWithChildren
  '/articles/$articleId': typeof StudioArticlesArticleIdRoute
  '/pages/$articleId': typeof StudioPagesArticleIdRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/articles/': typeof StudioArticlesIndexRoute
  '/pages/': typeof StudioPagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/sign-in': typeof SignInRoute
  '/communities': typeof StudioCommunitiesRoute
  '/homepage': typeof StudioHomepageRoute
  '/people': typeof StudioPeopleRoute
  '/team': typeof StudioTeamRoute
  '/api/media': typeof ApiMediaRouteWithChildren
  '/articles/$articleId': typeof StudioArticlesArticleIdRoute
  '/pages/$articleId': typeof StudioPagesArticleIdRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/articles': typeof StudioArticlesIndexRoute
  '/pages': typeof StudioPagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_studio': typeof StudioRouteWithChildren
  '/access-denied': typeof AccessDeniedRoute
  '/sign-in': typeof SignInRoute
  '/_studio/articles': typeof StudioArticlesRouteWithChildren
  '/_studio/communities': typeof StudioCommunitiesRoute
  '/_studio/homepage': typeof StudioHomepageRoute
  '/_studio/pages': typeof StudioPagesRouteWithChildren
  '/_studio/people': typeof StudioPeopleRoute
  '/_studio/team': typeof StudioTeamRoute
  '/api/media': typeof ApiMediaRouteWithChildren
  '/_studio/articles/$articleId': typeof StudioArticlesArticleIdRoute
  '/_studio/pages/$articleId': typeof StudioPagesArticleIdRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/_studio/articles/': typeof StudioArticlesIndexRoute
  '/_studio/pages/': typeof StudioPagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/sign-in'
    | '/articles'
    | '/communities'
    | '/homepage'
    | '/pages'
    | '/people'
    | '/team'
    | '/api/media'
    | '/articles/$articleId'
    | '/pages/$articleId'
    | '/api/media/$id'
    | '/articles/'
    | '/pages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/sign-in'
    | '/communities'
    | '/homepage'
    | '/people'
    | '/team'
    | '/api/media'
    | '/articles/$articleId'
    | '/pages/$articleId'
    | '/api/media/$id'
    | '/articles'
    | '/pages'
  id:
    | '__root__'
    | '/'
    | '/_studio'
    | '/access-denied'
    | '/sign-in'
    | '/_studio/articles'
    | '/_studio/communities'
    | '/_studio/homepage'
    | '/_studio/pages'
    | '/_studio/people'
    | '/_studio/team'
    | '/api/media'
    | '/_studio/articles/$articleId'
    | '/_studio/pages/$articleId'
    | '/api/media/$id'
    | '/_studio/articles/'
    | '/_studio/pages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudioRoute: typeof StudioRouteWithChildren
  AccessDeniedRoute: typeof AccessDeniedRoute
  SignInRoute: typeof SignInRoute
  ApiMediaRoute: typeof ApiMediaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_studio': {
      id: '/_studio'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_studio/articles': {
      id: '/_studio/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof StudioArticlesRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/communities': {
      id: '/_studio/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof StudioCommunitiesRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/homepage': {
      id: '/_studio/homepage'
      path: '/homepage'
      fullPath: '/homepage'
      preLoaderRoute: typeof StudioHomepageRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/pages': {
      id: '/_studio/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof StudioPagesRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/people': {
      id: '/_studio/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof StudioPeopleRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/team': {
      id: '/_studio/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof StudioTeamRouteImport
      parentRoute: typeof StudioRoute
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_studio/articles/': {
      id: '/_studio/articles/'
      path: '/'
      fullPath: '/articles/'
      preLoaderRoute: typeof StudioArticlesIndexRouteImport
      parentRoute: typeof StudioArticlesRoute
    }
    '/_studio/articles/$articleId': {
      id: '/_studio/articles/$articleId'
      path: '/$articleId'
      fullPath: '/articles/$articleId'
      preLoaderRoute: typeof StudioArticlesArticleIdRouteImport
      parentRoute: typeof StudioArticlesRoute
    }
    '/_studio/pages/': {
      id: '/_studio/pages/'
      path: '/'
      fullPath: '/pages/'
      preLoaderRoute: typeof StudioPagesIndexRouteImport
      parentRoute: typeof StudioPagesRoute
    }
    '/_studio/pages/$articleId': {
      id: '/_studio/pages/$articleId'
      path: '/$articleId'
      fullPath: '/pages/$articleId'
      preLoaderRoute: typeof StudioPagesArticleIdRouteImport
      parentRoute: typeof StudioPagesRoute
    }
    '/api/media/$id': {
      id: '/api/media/$id'
      path: '/$id'
      fullPath: '/api/media/$id'
      preLoaderRoute: typeof ApiMediaIdRouteImport
      parentRoute: typeof ApiMediaRoute
    }
  }
}

interface StudioArticlesRouteChildren {
  StudioArticlesArticleIdRoute: typeof StudioArticlesArticleIdRoute
  StudioArticlesIndexRoute: typeof StudioArticlesIndexRoute
}

const StudioArticlesRouteChildren: StudioArticlesRouteChildren = {
  StudioArticlesArticleIdRoute: StudioArticlesArticleIdRoute,
  StudioArticlesIndexRoute: StudioArticlesIndexRoute,
}

const StudioArticlesRouteWithChildren = StudioArticlesRoute._addFileChildren(
  StudioArticlesRouteChildren,
)

interface StudioPagesRouteChildren {
  StudioPagesArticleIdRoute: typeof StudioPagesArticleIdRoute
  StudioPagesIndexRoute: typeof StudioPagesIndexRoute
}

const StudioPagesRouteChildren: StudioPagesRouteChildren = {
  StudioPagesArticleIdRoute: StudioPagesArticleIdRoute,
  StudioPagesIndexRoute: StudioPagesIndexRoute,
}

const StudioPagesRouteWithChildren = StudioPagesRoute._addFileChildren(
  StudioPagesRouteChildren,
)

interface StudioRouteChildren {
  StudioArticlesRoute: typeof StudioArticlesRouteWithChildren
  StudioCommunitiesRoute: typeof StudioCommunitiesRoute
  StudioHomepageRoute: typeof StudioHomepageRoute
  StudioPagesRoute: typeof StudioPagesRouteWithChildren
  StudioPeopleRoute: typeof StudioPeopleRoute
  StudioTeamRoute: typeof StudioTeamRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioArticlesRoute: StudioArticlesRouteWithChildren,
  StudioCommunitiesRoute: StudioCommunitiesRoute,
  StudioHomepageRoute: StudioHomepageRoute,
  StudioPagesRoute: StudioPagesRouteWithChildren,
  StudioPeopleRoute: StudioPeopleRoute,
  StudioTeamRoute: StudioTeamRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

interface ApiMediaRouteChildren {
  ApiMediaIdRoute: typeof ApiMediaIdRoute
}

const ApiMediaRouteChildren: ApiMediaRouteChildren = {
  ApiMediaIdRoute: ApiMediaIdRoute,
}

const ApiMediaRouteWithChildren = ApiMediaRoute._addFileChildren(
  ApiMediaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudioRoute: StudioRouteWithChildren,
  AccessDeniedRoute: AccessDeniedRoute,
  SignInRoute: SignInRoute,
  ApiMediaRoute: ApiMediaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
