import {
  articleBaselines,
  articleContentChanges,
  articleRevisions,
  articles,
  communities,
  communityContactLocalizations,
  communityContacts,
  communityLocalizations,
  communityMedia,
  communityMediaLocalizations,
  communityServiceLocalizations,
  communityServices,
  homepageLayoutState,
  homepagePlacements,
  mediaAliases,
  mediaAssets,
  people,
  personContactLocalizations,
  personContacts,
  personLocalizations,
  personMedia,
  personMediaLocalizations,
  personPositionLocalizations,
  personPositions,
  publicationGroups,
  translationRuns,
} from "@ortodoksas-lt/db";
import { drizzle } from "drizzle-orm/d1";

const schema = {
  articleBaselines,
  articleContentChanges,
  articleRevisions,
  articles,
  communities,
  communityContactLocalizations,
  communityContacts,
  communityLocalizations,
  communityMedia,
  communityMediaLocalizations,
  communityServiceLocalizations,
  communityServices,
  homepageLayoutState,
  homepagePlacements,
  mediaAliases,
  mediaAssets,
  people,
  personContactLocalizations,
  personContacts,
  personLocalizations,
  personMedia,
  personMediaLocalizations,
  personPositionLocalizations,
  personPositions,
  publicationGroups,
  translationRuns,
};

export const getDatabase = (database: D1Database) =>
  drizzle(database, { schema });

export type StudioDatabase = ReturnType<typeof getDatabase>;
